test macos-13-large

diff --git a/.github/workflows/ci_e2e_tests.yml b/.github/workflows/ci_e2e_tests.yml
--- a/.github/workflows/ci_e2e_tests.yml
+++ b/.github/workflows/ci_e2e_tests.yml
@@ -69,7 +69,7 @@ jobs:
   run_e2e_tests:
     name: Run E2E Tests
     timeout-minutes: 20
-    runs-on: self-hosted
+    runs-on: macos-13-large
     needs: build_internal_samples
     steps:
       - name: Checkout repository
@@ -93,45 +93,54 @@ jobs:
           echo "Available APKs:"
           find apks -name "*.apk"
 
-      - name: Start Android Emulator and Run Tests
+      - name: Install Maestro
         run: |
-          # Start your existing emulator in background
-          $ANDROID_SDK_ROOT/emulator/emulator -avd Pixel_8 -no-snapshot -no-snapshot-save -no-snapshot-load -no-window -gpu swiftshader_indirect &
-          
-           # Wait for device to boot
-          adb wait-for-device
-          
-          # Wait until the device is fully booted
-          while [ "$(adb shell getprop sys.boot_completed 2>/dev/null)" != "1" ]; do
-          echo "Waiting for emulator to boot..."
-          sleep 2
-          done
-        
-          echo "Emulator is ready!"
-        
-          echo "Listing available APKs:"
-          find apks -name "*.apk"
-            
-          # verify emulator is running
-          adb devices
-          
-          echo "Installing APKs:"
-          find apks -name "*.apk" -exec adb install -r {} \;
-            
-          echo "Installed apps:"
-          adb shell pm list packages
-          
-          echo "Running Maestro web to native tests:"
-          maestro test .maestro/flows/web/connect_reject.yaml || echo "Test web_connect_reject failed but continuing"
-          maestro test .maestro/flows/web/connect_confirm.yaml || echo "Test web_connect_confirm failed but continuing"
-            
-#          echo "Running Maestro native to native tests:"
-#          maestro test .maestro/flows/native/connect_reject.yaml || echo "Test connect_reject failed but continuing"
-#          maestro test .maestro/flows/native/connect_confirm.yaml || echo "Test connect_confirm failed but continuing"
-#          maestro test .maestro/flows/native/personal_sign_reject.yaml || echo "Test sign_request_reject failed but continuing"
-#          maestro test .maestro/flows/native/personal_sign_confirm.yaml || echo "Test sign_request_confirm failed but continuing"
-            
+          curl -Ls "https://get.maestro.mobile.dev" | bash
+          export PATH="$PATH":"$HOME/.maestro/bin"
+          echo "$HOME/.maestro/bin" >> $GITHUB_PATH
+          maestro --version
 
+      - name: Setup Android SDK
+        uses: android-actions/setup-android@v2
+
+      - name: Start Android Emulator and Run Tests
+        uses: reactivecircus/android-emulator-runner@v2
+        with:
+          api-level: 32
+          target: google_apis
+          arch: x86_64
+          ram-size: 2048M
+          emulator-boot-timeout: 600 # 10min
+          cores: 2
+          profile: Nexus 6
+          avd-name: test_device
+          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
+          #          disable-animations: true
+          pre-emulator-launch-script: |
+            echo "Running pre emulator launch script. Printing the working directory now:"
+            pwd
+          script: |
+            echo "Listing available APKs:"
+            find apks -name "*.apk"
+            
+            # verify emulator is running
+            adb devices
+            
+            echo "Installing APKs:"
+            find apks -name "*.apk" -exec adb install -r {} \;
+            
+            echo "Installed apps:"
+            adb shell pm list packages
+            
+            echo "Running Maestro native to native tests:"
+            maestro test .maestro/flows/native/connect_reject.yaml || echo "Test connect_reject failed but continuing"
+            maestro test .maestro/flows/native/connect_confirm.yaml || echo "Test connect_confirm failed but continuing"
+            maestro test .maestro/flows/native/personal_sign_reject.yaml || echo "Test sign_request_reject failed but continuing"
+            maestro test .maestro/flows/native/personal_sign_confirm.yaml || echo "Test sign_request_confirm failed but continuing"
+
+#            echo "Running Maestro web to native tests:"
+#            maestro test .maestro/flows/web/connect_reject.yaml || echo "Test web_connect_reject failed but continuing"
+#            maestro test .maestro/flows/web/connect_confirm.yaml || echo "Test web_connect_confirm failed but continuing"
 
       - name: Find video files in project root
         if: always()
